kafka_producer:
  url:
    - "10.184.4.10:9092"
    - "10.184.4.11:9092"
    - "10.184.4.12:9092"
  #url: "datastream-redpanda-api-qa.datastream.svc.cluster.local:9092"
  topic: "QA_ITCH_"
  partition: 1
  batch_size: 512
  linger: 0
  acks: "0"
  maxproduceinflight: 1000000
  compression: "none"